runtime: go116

handlers:
  ## All API requests are prefixed with /v1
  - url: /v1/.*
    script: auto
    secure: always

  - url: /public
    static_dir: public
    secure: always

  - url: /
    static_files: build.html
    upload: build\.html
    secure: always
